### ISSUE TITLE
Nedaří se mi přihlásit

### ISSUE THREAD

**Issue by AlkoKod** [dfridrich/CzechDataBox#10]
Ahoj, dokázal byste mě prosím navést, kde dělám chybu? 

Fatal error: Uncaught SoapFault exception: [Client] DTD are not supported by SOAP in /vendor/dfridrich/czech-data-box/src/Api/DataBoxAccess.php:133 Stack trace: #0 /vendor/dfridrich/czech-data-box/src/Api/DataBoxAccess.php(133): SoapClient->__soapCall('GetOwnerInfoFro...', Array) #1 /vendor/dfridrich/czech-data-box/src/DataBoxSimpleApi.php(50): Defr\CzechDataBox\Api\DataBoxAccess->GetOwnerInfoFromLogin(Object(Defr\CzechDataBox\Api\tDummyInput)) #2 /datovkobot.php(67): Defr\CzechDataBox\DataBoxSimpleApi->getDataBoxInfo() #3 /wp-includes/class-wp-hook.php(308): cdb_plugin_settings_page('') #4 /wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #5 /wp-includes/plugin.php(517): WP_Hook->do_action(Array) #6 /wp-admin/admin.php(259): do_action('toplevel_page_c...') #7 {main} thrown in /vendor/dfridrich/czech-data-box/src/Api/DataBoxAccess.php on line 133

Vím o tom zhruba toto:

"Tato chyba znamená, že v knihovně CzechDataBox došlo k chybě při použití funkce SOAP (Simple Object Access Protocol) pro komunikaci s datovou schránkou. Konkrétně chyba říká, že DTD (Document Type Definition) není podporováno v rámci SOAP.

DTD je mechanismus pro definování struktury a obsahu XML dokumentu. V některých případech je používání DTD v SOAP zprávách zakázáno kvůli bezpečnostním důvodům, aby se předešlo potenciálním útokům a problémům s nežádoucím obsahem.

Chyba může být způsobena konkrétní konfigurací serveru, na kterém běží váš web, nebo možná omezením na straně datové schránky.

Pokud jste autor knihovny CzechDataBox, můžete se pokusit aktualizovat knihovnu a provést další ověření, zda byla tato chyba již opravena. Pokud nejste autorem knihovny, můžete kontaktovat autora nebo vývojářskou podporu a nahlásit tuto chybu, aby mohli provést opravu.

Pokud potřebujete další pomoc při řešení této chyby, můžete také zkontaktovat svého hostingového poskytovatele, aby vám pomohl s konfigurací serveru nebo poskytl další informace o tomto problému."

**Comment by meesha81** [comment]
Tuto chybu to píše když zadáváte špatné jméno/heslo.

**Comment by AlkoKod** [comment]
Díky! Nakonec to vyřešily ostré údaje místo testovacího prostředí.

Zasláno z Outlooku pro Android<https://aka.ms/AAb9ysg>
________________________________
